name: Push to Deta Space
on: push

jobs:
  push-to-deta-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Deta Space CLI
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo "$HOME/.detaspace/bin" >> $GITHUB_PATH
          echo "SPACE_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Get short SHA
        run: |
          echo "SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Push changes to Deta Space
        run: |
          space link --id "${{ secrets.PROJECT_ID }}"
          space push -t "${{ env.SHA }}"
